const subjects = [
    "Accounting",
    "African American Studies",
    "Anthropology",
    "Art",
    "Biochemistry",
    "Biology",
    "Business Administration",
    "Chemistry",
    "Cinema Media",
    "Communications",
    "Computer Science",
    "Economics",
    "Education",
    "English",
    "Environmental Science",
    "Film",
    "Finance",
    "French",
    "Geography",
    "Health Science",
    "Honors",
    "Human Services",
    "Information Technology",
    "Management",
    "Marketing",
    "Mathematics",
    "Music",
    "Nursing",
    "Philosophy",
    "Physical Education",
    "Political Science",
    "Psychology",
    "Sociology",
    "Spanish",
    "Theatre"
]

export default subjects;